--------------------------------------------------------
--  File created - Wednesday-September-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DRIVER
--------------------------------------------------------

  CREATE TABLE "SYS"."DRIVER" 
   (	"DRIVER_ID" NUMBER(38,0), 
	"FIRST_NAME" VARCHAR2(26 BYTE), 
	"SURNAME" VARCHAR2(26 BYTE), 
	"DRIVER_CODE" VARCHAR2(26 BYTE), 
	"PHONE_NUM" VARCHAR2(26 BYTE), 
	"ADDRESS" VARCHAR2(26 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.DRIVER
SET DEFINE OFF;
Insert into SYS.DRIVER (DRIVER_ID,FIRST_NAME,SURNAME,DRIVER_CODE,PHONE_NUM,ADDRESS) values (81011,'Buthelezi','Marshall','C1','0725698547','18 Leopard creek');
Insert into SYS.DRIVER (DRIVER_ID,FIRST_NAME,SURNAME,DRIVER_CODE,PHONE_NUM,ADDRESS) values (81012,'Tina','Mtati','C','0636984178','12 Cape rd');
Insert into SYS.DRIVER (DRIVER_ID,FIRST_NAME,SURNAME,DRIVER_CODE,PHONE_NUM,ADDRESS) values (81013,'Jono','Mvuyisi','EC1','0725648965','15 Circle lane');
Insert into SYS.DRIVER (DRIVER_ID,FIRST_NAME,SURNAME,DRIVER_CODE,PHONE_NUM,ADDRESS) values (81014,'Richard','Smith','C1','0623116598','18 Beach rd');
Insert into SYS.DRIVER (DRIVER_ID,FIRST_NAME,SURNAME,DRIVER_CODE,PHONE_NUM,ADDRESS) values (81015,'Brett','Smith','EB','0883521457','55 Summer lane');
