--------------------------------------------------------
--  File created - Wednesday-September-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VEHICLE
--------------------------------------------------------

  CREATE TABLE "SYS"."VEHICLE" 
   (	"VIN_NUMBER" VARCHAR2(26 BYTE), 
	"VEHICLE_TYPE" VARCHAR2(26 BYTE), 
	"MILEAGE" NUMBER(38,0), 
	"COLOUR" VARCHAR2(26 BYTE), 
	"MANUFACTURER" VARCHAR2(26 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.VEHICLE
SET DEFINE OFF;
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA55858541','Cutaway van chassis',115352,'RED','MAN');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA51858542','Flatbed truck',315856,'BLUE','ISUZU');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA35858543','Medium Standard Truck',789587,'SILVER','MAN');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA15851545','Flatbed truck',555050,'WHITE','TATA');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA35868540','Cutaway van chassis',79058,'WHITE','ISUZU');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA65858541','Cutaway van chassis',215352,'RED','MAN');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA61858542','Flatbed truck',215856,'BLUE','ISUZU');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA65858543','Medium Standard Truck',889587,'SILVER','MERC');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA65851545','Flatbed truck',155050,'WHITE','MAN');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA65868540','Cutaway van chassis',19058,'WHITE','ISUZU');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA75858541','Cutaway van chassis',315352,'RED','MAN');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA71858542','Flatbed truck',115856,'BLUE','ISUZU');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA75858543','Medium Standard Truck',989587,'SILVER','MAN');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA17851545','Flatbed truck',755050,'WHITE','TATA');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA75868540','Cutaway van chassis',29058,'WHITE','ISUZU');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA85858541','Cutaway van chassis',515352,'RED','MERC');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA81858542','Flatbed truck',715856,'BLUE','ISUZU');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA85858543','Medium Standard Truck',789587,'SILVER','MAN');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA85851545','Flatbed truck',955050,'WHITE','TATA');
Insert into SYS.VEHICLE (VIN_NUMBER,VEHICLE_TYPE,MILEAGE,COLOUR,MANUFACTURER) values ('1ZA85868540','Cutaway van chassis',39058,'WHITE','MERC');
